#! /usr/bin/env perl

use strict;
use warnings;
use Carp::Always;

use constant { TRUE => 1, FALSE => 0 };

use File::Basename;
use Getopt::Std;

our $opt_i;
our $opt_h;

sub usage {
  my $progname = basename($0);
  print STDERR "Usage: $progname [options] REGEXP \n";
  print STDERR "-i - ignore case\n";
  print STDERR "-h - print help\n";
  exit(@_);
}

my $stat = getopts('ih');
if (!$stat) {
  usage(1);
}
if ($opt_h) {
  usage();
}
my ($re) = @ARGV;
if ( !defined($re) ) {
  usage(1);
}

my $compiled_re;
if ( $opt_i ) {
  $compiled_re = qr/$re/i;
} else {
  $compiled_re = qr/$re/;
}


while (<STDIN>) {
  if ( /^# assembly_accession / ) {
    print;
    next;
  }
  if ( /^# / ) {
    next;
  }
  if ( $_ =~ $compiled_re ) {
    print;
  }
}
